<?php

namespace IngOscar\LogErrorHanlder;

use Illuminate\Support\ServiceProvider;

class LogErrorHandlerServiceProvider extends ServiceProvider
{
    public function boot(){

//        $this->load
        $this->publishes([
            __DIR__.'/../app/Exceptions' => base_path('app/Exceptions'),
        ], 'leh-excpetion-class');

        $this->publishes([
            __DIR__.'/../app/Models' => base_path('app/Models'),
        ], 'leh-model');

        $this->publishes([
            __DIR__.'/../database/migrations' => database_path('migrations'),
        ], 'leh-migration');

        $this->loadRoutesFrom(__DIR__ . '/routes/web.php');




    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
